# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/msg?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: root
        password: root
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    mail:
        host: localhost
        port: 25
        username:
        password:
    messages:
        cache-seconds: 1
    thymeleaf:
        cache: false
    profiles:
        include: swagger # automatically set the 'swagger' profile

    hosts:
        baseUrl: https://kong-qa.ailiens.com:8443
        mycroftEventPath: /event
    rabbit:
         host:  localhost
         queueLimit: 5
         timeout: 10000
         threadLifeTime: 10000
         sleepInterval: 5000
         maxWaitTime: 15
         username:
         password:
         poolSize: 5
    hazelcast:
         aws: false
         awsUrl: http://169.254.169.254
         instanceName: msg
         port: 5701
         accessKey: test
         secretKey: test
         regionCode: us-east-1
         tagKey: application2
         tagValue: msg


    keycloakCreds:
        keycloakGetAccessTokenUrl: https://keycloak-qa.ailiens.com/auth/realms/AILSecureQA/tokens/grants/access
        Authorization: Basic b2RpblFBOjUwYjgwZDQ3LWIxMDAtNDNhMC1iMzU1LTNhMmEwYWYyYjA1MQ==
        cacheDuration: 10
        map:
            NODEUSER:
                username: nodeuser
                password: qanode
                clientId: odinQA

liquibase:
    contexts: dev

server:
    port: 8050

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    cache: # Hibernate 2nd level cache, used by CacheConfiguration
        timeToLiveSeconds: 3600
        ehcache:
            maxBytesLocalHeap: 16M
    security:
        rememberMe:
            # security key (this key should be unique for your application, and kept secret)
            key: d13e54a275bc6612a295696e677463293f17349a
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: msg@localhost
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: msg
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
